### ISSUE TITLE
raise ValueError, "mtl file doesn't start with newmtl stmt"

### ISSUE THREAD

**Issue by PiseyYou** [GeekLiB/AR-BXT-AR4Python#2]
the code seems to compile in python2, I change the code print type to python3, but the error occur, something need to change?

> Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "ar_demo.py", line 12, in <module>
    import BAR4Py.objloader as objloader
  File "/home/pisey/anaconda3/envs/robosense/AR-BXT-AR4Python/demo/BAR4Py/objloader.py", line 14
    raise ValueError, "mtl file doesn't start with newmtl stmt"
                    ^
SyntaxError: invalid syntax

**Comment by BryceQing** [comment]
You should use python3 grammar that add ():

raise (ValueError, "mtl file doesn't start with newmtl stmt")
